export const SET_QUERY = "SET_QUERY";
export const SET_LETTER = "SET_LETTER";
export const SET_TYPE = "SET_TYPE";

export const SET_TAB = "SET_TAB";

export const POKEMONS_FETCHING = "POKEMONS_FETCHING";
export const POKEMONS_FETCH = "POKEMONS_FETCH";
export const POKEMONS_FETCH_ERROR = "POKEMONS_FETCH_ERROR";

export const POKEMON_FETCHING = "POKEMON_FETCHING";
export const POKEMON_FETCH = "POKEMON_FETCH";
export const POKEMON_FETCH_ERROR = "POKEMON_FETCH_ERROR";

export const POKEMON_LOCAL_ADD = "POKEMON_LOCAL_ADD";
export const POKEMON_LOCAL_REMOVE = "POKEMON_LOCAL_REMOVE";
export const POKEMON_LOCAL_REMOVE_ALL = "POKEMON_LOCAL_REMOVE_ALL";

export const POKEMONS_GET = "POKEMONS_GET";
export const POKEMON_GET = "POKEMON_GET";